spring:
  profiles:
    active: -dev

---

server:
  port: 8001
spring:
  profiles: dev
  application:
    name: integral-gam-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.22.58:3306/excellentintegral_java_dev?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: jifen
    password: jifen
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.dmsdbj.cloud.integralgamapi.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
  client:
    service-url:
      #客户端注册进eureka服务列表内
      defaultZone: http://192.168.22.107:20002/eureka/
  instance:
    #注册到eureka后，status的名字（服务在eureka的唯一标志）
    instance-id: gam-8001
    lease-expiration-duration-in-seconds: 15 # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 5 # #服务刷新时间配置，每隔这个时间会主动心跳一次
    #访问路径可以显示IP地址
    prefer-ip-address: true

info:
  app.name: provider-dept-8001
  company.name: www.jarvis.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

server:
  port: 8001
spring:
  profiles: test
  application:
    name: integral-gam-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.22.58:3306/excellentintegral_java_dev?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: jifen
    password: jifen
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.dmsdbj.cloud.integralgamapi.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
  client:
    service-url:
      #客户端注册进eureka服务列表内
      defaultZone: http://192.168.22.107:20002/eureka/
  instance:
    #注册到eureka后，status的名字（服务在eureka的唯一标志）
    instance-id: gam-8001
    #访问路径可以显示IP地址
    prefer-ip-address: true

info:
  app.name: provider-dept-8001
  company.name: www.jarvis.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
